version: 2.1

defaults: &defaults
  machine:
    image: ubuntu-1604:201903-01

jobs:
  build:
    <<: *defaults

    steps:
      - run: wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | sudo apt-key add -
      - run: sudo apt-get install -y software-properties-common
      - run: sudo add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/
      - run: sudo apt-get update && sudo apt-get install adoptopenjdk-11-openj9 tree graphviz maven
      - run: sudo update-alternatives --set java /usr/lib/jvm/adoptopenjdk-11-openj9-amd64/bin/java
      - run: sudo update-alternatives --set javac /usr/lib/jvm/adoptopenjdk-11-openj9-amd64/bin/javac
      - checkout
      - run:
          name: Build and Test
          command: mvn -B package
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
      - run:
          name: Analyze on SonarCloud
          command: mvn -B clean verify sonar:sonar

  build-docs:
    <<: *defaults

    steps:
      - run: wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | sudo apt-key add -
      - run: sudo apt-get install -y software-properties-common
      - run: sudo add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/
      - run: sudo apt-get update && sudo apt-get install adoptopenjdk-11-openj9 tree graphviz maven
      - run: sudo update-alternatives --set java /usr/lib/jvm/adoptopenjdk-11-openj9-amd64/bin/java
      - run: sudo update-alternatives --set javac /usr/lib/jvm/adoptopenjdk-11-openj9-amd64/bin/javac
      - checkout
      - run:
          name: Install Graphiz
          command: sudo apt-get install graphviz
      - run:
          name: Build Arc42
          command: mvn -Parc42
      - store_artifacts:
          path: ~/target/generated-docs/
      - persist_to_workspace:
            root: target
            paths:
              - generated-docs

workflows:
  version: 2.1
  build-n-deploy:
    jobs:
      - build:
          context: SonarCloud
          filters:
            tags:
              only: /.*/
      - build-docs:
          requires:
            - build
          filters:
            tags:
              only: /.*/