// *** WARNING: DO NOT MODIFY *** This is a generated Java source code! 
// 
// Generated by LF-ET 2.1.5 (200430a), https://www.lohrfink.de/lfet
// From decision table
// "/opt/data/github/a4ad/application/src/main/resources/ExecuteDeployment.lfet"
// 04.05.2020 01:27
// 

// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.Dt.ini not found
// used LF-ET 2.1.5 (200430a) build in default

package com.github.a4ad.application.deployment.execute;

final class ExecuteDeploymentRulesClass
{
    void execute(IExecuteDeploymentET iface)
    {
 
    // Prolog Standard <----

        // Prolog Decision Table ---->
        // $$InterfaceRulesClassName=ExecuteDeploymentRulesClass
        // $$InterfaceName=IExecuteDeploymentET
        // $$Package=com.github.a4ad.application.deployment.execute
        // Prolog Decision Table <----
        
        int ruleGroup = 1;
        boolean exit = false;
        
        while ( !exit )
        {
            exit = true;
            
            if ( ruleGroup == 1 )
            {
                // Rule R01 ---->
                
                iface.doTrace("ExecuteDeployment", "20200504.012718", 2, 1);
                
                ruleGroup = 2;
                exit = false;
                
                // Rule R01 <----
            }
            else
            {
                // Rule R02 ---->
                
                iface.doTrace("ExecuteDeployment", "20200504.012718", 2, 2);
                iface.doStartCopyArtifactToTargetServers();
                
                exit = true;
                
                // Rule R02 <----
            }
        
        }
        
        // Epilog Standard ---->
        // profile LFET.Java.Epilog.Standard.Interface.Dt.ini not found
        // used LF-ET 2.1.5 (200430a) build in default

    }

}
 
// Epilog Standard <----

// End of generated Java source code
// Generated by LF-ET 2.1.5 (200430a), https://www.lohrfink.de/lfet

