// *** WARNING: DO NOT MODIFY *** This is a generated Java source code! 
// 
// Generated by LF-ET 2.1.5 (200430a), https://www.lohrfink.de/lfet
// From decision table
// "/opt/data/github/a4ad/application/src/main/resources/ExecuteDeployment.lfet"
// 04.05.2020 01:27
// 
// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.ini not found
// used LF-ET 2.1.5 (200430a) build in default

package com.github.a4ad.application.deployment.execute;

interface IExecuteDeploymentET
{
 
    // Prolog Standard <----

    // Prolog Decision Table ---->
    // $$InterfaceRulesClassName=ExecuteDeploymentRulesClass
    // $$InterfaceName=IExecuteDeploymentET
    // $$Package=com.github.a4ad.application.deployment.execute
    // Prolog Decision Table <----
    
    /** 
     * <b>A01: Start copy artifact to target servers</b>
     */
    void doStartCopyArtifactToTargetServers();
    
    void doTrace(java.lang.String dtName, java.lang.String version, int rules, int rule);

    // Epilog Standard ---->
    // profile LFET.Java.Epilog.Standard.Interface.ini not found
    // used LF-ET 2.1.5 (200430a) build in default

}
 
// Epilog Standard <----

// End of generated Java source code
// Generated by LF-ET 2.1.5 (200430a), https://www.lohrfink.de/lfet

